spring:
  datasource:
    url: ${DATA_SOURCE_URL:jdbc:mysql://avnadmin:AVNS_G40tXtDUqJn_g-6PGYe@mysql-2339a621-lakshman-6868.a.aivencloud.com:13707/gld-retail?ssl-mode=REQUIRED}
    username: ${DATA_USERNAME:avnadmin}
    password: ${DATA_PASSWORD:AVNS_G40tXtDUqJn_g-6PGYe}
#    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      leakDetectionThreshold: 30000
  jpa:
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  server:
    error:
      whitelabel:
        enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.billing: DEBUG
