create table item_master (id bigint not null auto_increment,
item_code varchar(50),
item_huid varchar(50),
item_metal varchar(100),
item_name varchar(100),
item_quality varchar(10),
mc decimal(19,2),
pcs integer not null,
stone_name varchar(100),
stone_pcs integer not null,
stone_weight decimal(19,3),
stone_wt_in_cts decimal(19,3),
tag_no varchar(255),
va_percentage decimal(19,2),
wastage_in_gms decimal(19,3),
weight decimal(19,3),
primary key (id))